repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/jackdewinter/pymarkdown
    rev: main
    hooks:
    - id: pymarkdown
      args:
      - -d
      - MD041
      - MD013
      - scan
